[versions]
kotlin = "2.2.21"
junit = "6.0.1"
ktlint-gradle = "14.0.1"
classgraph = "4.8.184"
kotlinx-coroutines = "1.10.2"
slf4j = "2.0.17"
logback = "1.5.19"
kotlin-logging = "7.0.13"

[libraries]
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j"}
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }